# https://www.appveyor.com/docs/lang/nodejs-iojs/#testing-under-multiple-versions-of-nodejs-or-iojs
environment:
  fast_finish: true
  matrix:
    - nodejs_version: "7"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node -p process.arch
  - node -p process.version

test_script:
  - node inspect -p 655555

build: off

version: "{build}"
