# https://www.appveyor.com/docs/lang/nodejs-iojs/#testing-under-multiple-versions-of-nodejs-or-iojs
environment:
  fast_finish: true
  matrix:
    - nodejs_version: "7"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node -p process.arch
  - node -p process.version
  - wget node-v8.0.0-nightly20170430aa3eab00da-win-x64.zip
  - 7z x node-v8.0.0-nightly20170430aa3eab00da-win-x64.zip

test_script:
  - node-v8.0.0-nightly20170430aa3eab00da-win-x64\\node.exe debug -p 655555

build: off

version: "{build}"
